spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dataModel?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true
server:
    port: 8181
        
